"""empty message

Revision ID: 2810496bd8d5
Revises: 609bf47ac692
Create Date: 2016-03-12 20:19:23.997055

"""

# revision identifiers, used by Alembic.
revision = '2810496bd8d5'
down_revision = '609bf47ac692'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('targetmode', sa.Integer(), nullable=True),
    sa.Column('target', sa.Integer(), nullable=True),
    sa.Column('sender', sa.Integer(), nullable=True),
    sa.Column('msg', sa.String(length=1025), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    ### end Alembic commands ###
