"""empty message

Revision ID: 40574c555d45
Revises: 2810496bd8d5
Create Date: 2016-03-12 20:20:59.938717

"""

# revision identifiers, used by Alembic.
revision = '40574c555d45'
down_revision = '2810496bd8d5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'date')
    ### end Alembic commands ###
