"""empty message

Revision ID: 609bf47ac692
Revises: d8dd58991d72
Create Date: 2016-03-12 20:17:15.843424

"""

# revision identifiers, used by Alembic.
revision = '609bf47ac692'
down_revision = 'd8dd58991d72'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('target', sa.Integer(), nullable=True))
    op.drop_column('messages', 'target_user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('target_user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'target')
    ### end Alembic commands ###
