"""empty message

Revision ID: d8dd58991d72
Revises: e0de5f46a1da
Create Date: 2016-03-12 19:53:30.326543

"""

# revision identifiers, used by Alembic.
revision = 'd8dd58991d72'
down_revision = 'e0de5f46a1da'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('target_user', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('targetmode', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'targetmode')
    op.drop_column('messages', 'target_user')
    ### end Alembic commands ###
