"""empty message

Revision ID: f973bc56a35e
Revises: None
Create Date: 2016-04-12 19:54:26.049631

"""

# revision identifiers, used by Alembic.
revision = 'f973bc56a35e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queued_commands', sa.Column('completed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queued_commands', 'completed')
    ### end Alembic commands ###
